language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ng lint
  - ng build --prod --base-href https://niawjunior.github.io/angular-drag-drop/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-drag-drop
  on:
    branch: master
